sudo: false
dist: trusty
language: rust
# No environment varibles by default
env:
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

matrix:
  fast_finish: true
  include:
    - rust: stable
      env: COVERALLS=true
  allow_failures:
    - rust: nightly
    - env: COVERALLS=true

# run builds for all the trains (and more)
rust:
  - nightly
  - beta
  - stable
notifications:
  irc: chat.freenode.net#radare-rsoc
  email: false
os:
  - linux
before_script:
  - |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH
  # Clone and build radare2
  - |
      git clone https://github.com/radare/radare2.git &&
      cd ./radare2 && ./sys/install.sh && cd ../

script:
  - |
    travis-cargo build &&
    travis-cargo test &&
    travis-cargo bench
after_success:
  - travis-cargo --only stable coveralls --no-sudo --verify
  - travis-cargo --only stable doc-upload
script:
  - |
    cargo build &&
    cargo bench;
    if [ "$COVERALLS" != "true" ];
      then cargo test;
    fi
# The coveralls env runs tests as part of its run
after_success:
  - |
    if [ "$COVERALLS" = "true" ]; 
      then travis_wait 30 cargo coveralls --exclude-pattern tests/; 
    fi
# Restore automatic doc updating when cargo-travis gets this feature
#  travis-cargo --only stable doc-upload
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure:"6Hai838Ii8T5f9g2HvioILGulY3aoH6gEQudAzeRW/EwJYyIS3dnd+dqzklxZg5NzDfS2iqcVc8KplevRviR6WLdGnpAWNyLqni+hJepNgpJESPH4g7jYYlmVK7VCXvhWKNpoYXd3Gjx6CLCpF2NVX3cnSKAgPz1SMMWm+ulAI8Bqj6NnG53fme6siQwyajVdKcsvawim2JlDtIl0sTsJDpAYr7ivQvc1MCjvLY1PUV5cUEGhnOJFv3RQS32gklGvk96FKFyb0kiPIsCvIIL4ZzeP8SpiJyW1DYNlUqMvxGwSzie8mowdNvh3gbzj9ll7y9B1bTYbaYY8ETLbqDtBZF52rC+4Cnxkbj9275ij7lvJcfr1wBvN1DxVmUnfWyWUBi2aQpNePmKJvMxLSlKW+U5diQrf/NS34gmblccv1aPQszT11Le5kVhZm4KEXQWvh/L4+NO/DOWRmHvBjHH+Ov/sHx59jbgd/OYsiIQ0WIWKaCIT/oU3w6jTBCeKzX7arw0k8hQlNdOKOJCdjAHsI50kln2yXm4rJnVnXaX7spJP1v00csbK95fjxn8dp/f4L6gWrBQzmeKTLjrMFQQTHAx+JC3Oigt28eKwkJVIo9cO25wdUD52rjPPTOMqVHONqpHq735sMYfDItKAG7FmQ427ZgfQRuRblvjijcexBM="
