clone_depth: 1
environment:
  matrix:
    - channel: stable
      target: i686-pc-windows-msvc
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: beta
      target: i686-pc-windows-msvc
    - channel: beta
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: i686-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc

    - channel: stable
      target: i686-pc-windows-gnu
    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: beta
      target: i686-pc-windows-gnu
    - channel: beta
      target: x86_64-pc-windows-gnu
    - channel: nightly
      target: i686-pc-windows-gnu
    - channel: nightly
      target: x86_64-pc-windows-gnu
install:
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init -yv --default-toolchain %channel% --default-host %target%
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    - rustc -vV
    - cargo -vV
build_script:
    - cargo build -vv
test_script:
    - cargo test -vv
deploy: off
