[package]
name = "arch"
version = "0.1.0"
edition = "2018"

[dependencies]
lazy_static = "1.4.0"

[dependencies.r2api]
git = "https://github.com/radare/radare2-r2pipe-api"

[dependencies.r2pipe]
git = "https://github.com/radareorg/r2pipe.rs"
